### PR TITLE
[RevealLatte] Added CallStaticMethodsRule to tests

### PR DESCRIPTION
**Pull request by lulco**
I missed this already in https://github.com/symplify/symplify/pull/3661/files/70e4d4995136a1ebd329d90bc58547cd7e0769af#r722065671 finally I found solution

### CODE REVIEW

**Comment by lulco** [comment]
hmm something has changed in twig? :) I didn't touch it :D

btw I thought if I'm in organisation,  I don't need fork :)

**Comment by lulco** [comment]
tests fixed in https://github.com/revealphp/reveal/pull/15

**Comment by TomasVotruba** [comment]
> btw I thought if I'm in organisation, I don't need fork :)

Github has too many options to make this easy :D I'm trying to setup better role. I've changed your role to outside collaborator, that has more options.

**Comment by TomasVotruba** [comment]
> I missed this already in [symplify/symplify/pull/3661/files/70e4d4995136a1ebd329d90bc58547cd7e0769af#r722065671](https://github.com/symplify/symplify/pull/3661/files/70e4d4995136a1ebd329d90bc58547cd7e0769af#r722065671) finally I found solution

:+1: :clap:

**Pull request merged**
